trigger:
  - main  # Or your specific branch name

pool:
  name: Default  # Name of your self-hosted agent pool

variables:
  pythonVersion: '3.9'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: CopyFiles@2
    inputs:
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
      ArtifactName: 'drop'
