trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Your self-hosted agent pool name

variables:
  azureWebAppName: 'EmployeeWise'  # Your exact web app name
  packagePath: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'

steps:

# Use Python 3.9 (skip if your self-hosted agent already uses 3.9)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

# Install required packages
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Zip the app contents
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packagePath)'
    replaceExistingArchive: true
  displayName: 'Archive Flask App'

# Publish the zipped artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifact'

# Deploy to Azure Web App (Linux)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1'  # ✅ Your service connection
    appType: 'webAppLinux'
    appName: '$(azureWebAppName)'
    package: '$(packagePath)'
  displayName: 'Deploy to Azure Web App'
