trigger:
  - main

pool:
  name: Default  # Your self-hosted Mac agent pool

steps:
  - script: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - task: CopyFiles@2
    inputs:
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/flaskapp.zip'
      ArtifactName: 'drop'
