trigger:
- main  # Or your actual working branch

pool:
  name: Default  # Change if your self-hosted agent pool has another name

variables:
  pythonVersion: '3.9'
  webAppName: '<YOUR_AZURE_WEBAPP_NAME>'  # Replace with your actual App Service name
  artifactName: 'flaskapp'
  zipName: 'flaskapp.zip'

steps:

# Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# Install dependencies
- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Create deployment package
- script: |
    mkdir deploy_package
    cp -r app templates main.py requirements.txt deploy_package/
  displayName: 'Package Flask app files'

# Zip for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'deploy_package'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(zipName)'
    replaceExistingArchive: true
  displayName: 'Zip deployment package'

# Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(zipName)'
    ArtifactName: '$(artifactName)'
  displayName: 'Publish build artifact'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION_NAME>'  # Must match your Azure DevOps service connection
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/$(zipName)'
  displayName: 'Deploy to Azure App Service'
